services:
  - type: pserv
    name: synaplearn-sql
    runtime: image
    plan: standard
    region: singapore
    image:
      url: mcr.microsoft.com/mssql/server:2022-latest
    envVars:
      - key: ACCEPT_EULA
        value: Y
      - key: MSSQL_PID
        value: Developer
      - key: MSSQL_SA_PASSWORD
        generateValue: true
      - key: MSSQL_MEMORY_LIMIT_MB
        value: "1536"
    disk:
      name: sqlserver-data
      mountPath: /var/opt/mssql
      sizeGB: 10

  - type: web
    name: synaplearn-web
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    healthCheckPath: /healthz
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: ASPNETCORE_FORWARDEDHEADERS_ENABLED
        value: "true"
      - key: AllowedHosts
        value: "*"
      - key: DB_HOST
        fromService:
          type: pserv
          name: synaplearn-sql
          property: host
      - key: DB_PORT
        value: "1433"
      - key: DB_NAME
        value: myDB
      - key: DB_USER
        value: sa
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: synaplearn-sql
          envVarKey: MSSQL_SA_PASSWORD
      - key: DB_ENCRYPT
        value: "false"
      - key: DB_TRUST_SERVER_CERTIFICATE
        value: "true"
      - key: Jwt__Issuer
        value: WedProject
      - key: Jwt__Audience
        value: WedProjectClient
      - key: Jwt__UseAsymmetric
        value: "false"
      - key: Jwt__AutoGenerateDevelopmentKey
        value: "false"
      - key: Jwt__SecretKey
        generateValue: true
      - key: GoogleAuth__ClientId
        sync: false
      - key: Groq__GroqApiKey
        sync: false
      - key: Gemini__ApiKey
        sync: false
      - key: Smtp__Host
        sync: false
      - key: Smtp__Port
        value: "587"
      - key: Smtp__EnableSsl
        value: "true"
      - key: Smtp__Username
        sync: false
      - key: Smtp__Password
        sync: false
      - key: Smtp__FromEmail
        value: no-reply@synaplearn.local
      - key: Smtp__FromName
        value: SynapLearn
