using System.Security.Cryptography;
using System.Text;
using Microsoft.IdentityModel.Tokens;
using Web_Project.Models;

namespace Web_Project.Security
{
    public sealed class JwtSigningMaterial
    {
        private const string DevelopmentPrivateKeyRelativePath = ".dotnet/jwt-dev/private-key.pem";
        private const string DevelopmentPublicKeyRelativePath = ".dotnet/jwt-dev/public-key.pem";

        public SecurityKey SigningKey { get; }

        public SecurityKey ValidationKey { get; }

        public string Algorithm { get; }

        public bool IsAsymmetric { get; }

        public bool IsEphemeral { get; }

        private JwtSigningMaterial(
            SecurityKey signingKey,
            SecurityKey validationKey,
            string algorithm,
            bool isAsymmetric,
            bool isEphemeral)
        {
            SigningKey = signingKey;
            ValidationKey = validationKey;
            Algorithm = algorithm;
            IsAsymmetric = isAsymmetric;
            IsEphemeral = isEphemeral;
        }

        public SigningCredentials CreateSigningCredentials()
        {
            return new SigningCredentials(SigningKey, Algorithm);
        }

        public static JwtSigningMaterial Create(JwtSettings settings, string contentRootPath)
        {
            if (settings.UseAsymmetric)
            {
                return CreateAsymmetric(settings, contentRootPath);
            }

            return CreateSymmetric(settings);
        }

        private static JwtSigningMaterial CreateSymmetric(JwtSettings settings)
        {
            if (string.IsNullOrWhiteSpace(settings.SecretKey))
            {
                throw new InvalidOperationException("Jwt:SecretKey is required when Jwt:UseAsymmetric=false.");
            }

            var keyBytes = Encoding.UTF8.GetBytes(settings.SecretKey);
            if (keyBytes.Length < 32)
            {
                throw new InvalidOperationException("Jwt:SecretKey must be at least 32 bytes.");
            }

            var key = new SymmetricSecurityKey(keyBytes);
            return new JwtSigningMaterial(
                key,
                key,
                SecurityAlgorithms.HmacSha256,
                isAsymmetric: false,
                isEphemeral: false);
        }

        private static JwtSigningMaterial CreateAsymmetric(JwtSettings settings, string contentRootPath)
        {
            var privateKeyPath = ResolvePath(settings.PrivateKeyPemPath, contentRootPath);
            var publicKeyPath = ResolvePath(settings.PublicKeyPemPath, contentRootPath);
            var privateKeyPem = ResolvePem(
                settings.PrivateKeyPem,
                privateKeyPath);

            var publicKeyPem = ResolvePem(
                settings.PublicKeyPem,
                publicKeyPath);

            if (string.IsNullOrWhiteSpace(privateKeyPem))
            {
                if (!settings.AutoGenerateDevelopmentKey)
                {
                    throw new InvalidOperationException(
                        "Jwt asymmetric mode is enabled but private key is missing. Set Jwt:PrivateKeyPem or Jwt:PrivateKeyPemPath.");
                }

                return CreatePersistentDevelopmentAsymmetricKey(
                    settings,
                    string.IsNullOrWhiteSpace(privateKeyPath)
                        ? Path.Combine(contentRootPath, DevelopmentPrivateKeyRelativePath)
                        : privateKeyPath,
                    string.IsNullOrWhiteSpace(publicKeyPath)
                        ? Path.Combine(contentRootPath, DevelopmentPublicKeyRelativePath)
                        : publicKeyPath);
            }

            using var privateRsa = RSA.Create();
            privateRsa.ImportFromPem(privateKeyPem);

            var signingRsa = RSA.Create();
            signingRsa.ImportParameters(privateRsa.ExportParameters(true));

            RSA validationRsa;
            if (string.IsNullOrWhiteSpace(publicKeyPem))
            {
                validationRsa = RSA.Create();
                validationRsa.ImportParameters(privateRsa.ExportParameters(false));
            }
            else
            {
                validationRsa = RSA.Create();
                validationRsa.ImportFromPem(publicKeyPem);
            }

            var signingSecurityKey = new RsaSecurityKey(signingRsa);
            var validationSecurityKey = new RsaSecurityKey(validationRsa);

            return new JwtSigningMaterial(
                signingSecurityKey,
                validationSecurityKey,
                SecurityAlgorithms.RsaSha256,
                isAsymmetric: true,
                isEphemeral: false);
        }

        private static JwtSigningMaterial CreatePersistentDevelopmentAsymmetricKey(
            JwtSettings settings,
            string privateKeyPath,
            string publicKeyPath)
        {
            var keySize = Math.Max(2048, settings.GeneratedKeySize);
            Directory.CreateDirectory(Path.GetDirectoryName(privateKeyPath) ?? ".");
            Directory.CreateDirectory(Path.GetDirectoryName(publicKeyPath) ?? ".");

            using var generated = RSA.Create(keySize);
            var privateKeyPem = generated.ExportRSAPrivateKeyPem();
            var publicKeyPem = generated.ExportSubjectPublicKeyInfoPem();

            File.WriteAllText(privateKeyPath, privateKeyPem);
            File.WriteAllText(publicKeyPath, publicKeyPem);

            var signingRsa = RSA.Create();
            signingRsa.ImportFromPem(privateKeyPem);

            var validationRsa = RSA.Create();
            validationRsa.ImportFromPem(publicKeyPem);

            return new JwtSigningMaterial(
                new RsaSecurityKey(signingRsa),
                new RsaSecurityKey(validationRsa),
                SecurityAlgorithms.RsaSha256,
                isAsymmetric: true,
                isEphemeral: false);
        }

        private static string ResolvePem(string inlinePem, string resolvedPemPath)
        {
            if (!string.IsNullOrWhiteSpace(inlinePem))
            {
                return inlinePem.Trim();
            }

            if (string.IsNullOrWhiteSpace(resolvedPemPath))
            {
                return string.Empty;
            }

            if (!File.Exists(resolvedPemPath))
            {
                return string.Empty;
            }

            return File.ReadAllText(resolvedPemPath).Trim();
        }

        private static string ResolvePath(string pemPath, string contentRootPath)
        {
            if (string.IsNullOrWhiteSpace(pemPath))
            {
                return string.Empty;
            }

            return Path.IsPathRooted(pemPath)
                ? pemPath
                : Path.Combine(contentRootPath, pemPath);
        }
    }
}
