deploy:
    name: Deploy To Server
    runs-on: ubuntu-latest
    needs: docker
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    environment:
      name: production

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Package application
        run: |
          tar --warning=no-file-changed --exclude=.git --exclude=.github --exclude=bin --exclude=obj -czf ${{ env.DEPLOY_PACKAGE }} .

      - name: Copy package to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: ${{ env.DEPLOY_PACKAGE }}
          target: "/tmp"

      - name: Extract and Run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            mkdir -p ${{ secrets.DEPLOY_PATH }}
            tar -xzf /tmp/${{ env.DEPLOY_PACKAGE }} -C ${{ secrets.DEPLOY_PATH }}
            cd ${{ secrets.DEPLOY_PATH }}
            echo "${{ secrets.ENV_DOCKER }}" > .env.docker
            docker compose --env-file .env.docker up -d --build
            rm /tmp/${{ env.DEPLOY_PACKAGE }}