name: CI/CD SynapLearn

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DEPLOY_PACKAGE: deploy-package.tgz
  PROJECT_NAME: Web_Project 



jobs:
  build-and-deploy:
    name: Build and Deploy to AWS
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish Application
        run: |
          dotnet publish ${{ env.PROJECT_NAME }}.csproj -c Release -o ./publish

      - name: Prepare Deployment Package
        run: |
          cp Dockerfile ./publish/
          cp docker-compose.yml ./publish/
          tar -czf ${{ env.DEPLOY_PACKAGE }} -C ./publish .

      - name: Copy package to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: ${{ env.DEPLOY_PACKAGE }}
          target: "/tmp"

      - name: Extract and Run on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            mkdir -p ${{ secrets.DEPLOY_PATH }}
            
            tar -xzf /tmp/${{ env.DEPLOY_PACKAGE }} -C ${{ secrets.DEPLOY_PATH }}
            
            cd ${{ secrets.DEPLOY_PATH }}
            
            echo "${{ secrets.ENV_DOCKER }}" > .env.docker
            
            docker compose --env-file .env.docker up -d --build
            
            rm /tmp/${{ env.DEPLOY_PACKAGE }}
            docker image prune -f